import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous"></link>
      <body className={inter.className} style={{ backgroundColor: '#f7fa9f' }}> {/* เพิ่มสีพื้นหลังที่นี่ */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px' }}>
          <h1>Natnicha</h1>
          <nav>
            <Link href="/">Home</Link>{" - "}
            <Link href="/pokemon">Pokemon</Link>{" - "}
            <Link href="/student">AboutMe</Link>
          </nav>
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
